export { default as AuthForm } from "./AuthForm/AuthForm";
export { default as AuthNav } from "./AuthNav/AuthNav";
export { default as AuthPicture } from "./AuthPicture/AuthPicture";
export { default as Header } from "./Header/Header";
export { default as WordsTable } from "./WordsTable/WordsTable";
export { default as WordsPagination } from "./WordsPagination/WordsPagination";
export { default as Dashboard } from "./Dashboard/Dashboard";
export { default as AddWordButton } from "./AddWordButton/AddWordButton";
export { default as AddWordForm } from "./AddWordForm/AddWordForm";
